# Generated by Django 5.2.1 on 2025-05-25 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_rename_is_featured_product_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
