# Generated by Django 5.2.1 on 2025-06-02 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
    name='age',
    field=models.IntegerField(null=True, blank=True),

        ),
        
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='region_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
